### ISSUE TITLE
Old cargo version with no stabilized support for edition 2021 fail to build cosmwasm-std

### ISSUE THREAD

**Issue by etienne-napoleone** [CosmWasm/rust-optimizer#73]
`uint-v0.9.2` changed to edition 2021 leading to error while trying to run rust-optimizer on a crate with deps to `uint ^0.9.0`. This includes cosmwasm-std.

### Quickfix

```toml
[dependencies]
uint = "=0.9.1"  # needed to fix uint to 2018 rust edition
cosmwasm-std = "0.16.2"
```
